"""Shared Event Schema v1 models for custom_chat plugin and web BFF."""

from custom_chat_schema.schema import (
    ERROR_CODES,
    INBOUND_TYPES,
    OUTBOUND_TYPES,
    PLATFORM_NAME,
    SCHEMA_VERSION,
    AudioUploadedPayload,
    FileUploadedPayload,
    ButtonClickPayload,
    ButtonSpec,
    SessionMetaPayload,
    SlashConfirmPayload,
    SlashPickPayload,
    ModelPickerPayload,
    AssistantNoticePayload,
    AssistantSegmentPayload,
    ClientRegisterPayload,
    CommandCreatePayload,
    DEFAULT_ALLOWED_UPLOAD_MIME_TYPES,
    EventEnvelope,
    MessageCancelPayload,
    MessageAttachment,
    MessageCreatePayload,
    build_outbound_event,
    parse_inbound_envelope,
)
from custom_chat_schema.mime import normalize_mime_type
from custom_chat_schema.settings import CustomChatSettings

__all__ = [
    "SCHEMA_VERSION",
    "PLATFORM_NAME",
    "ERROR_CODES",
    "INBOUND_TYPES",
    "OUTBOUND_TYPES",
    "DEFAULT_ALLOWED_UPLOAD_MIME_TYPES",
    "CustomChatSettings",
    "EventEnvelope",
    "MessageAttachment",
    "MessageCreatePayload",
    "ClientRegisterPayload",
    "CommandCreatePayload",
    "AudioUploadedPayload",
    "FileUploadedPayload",
    "MessageCancelPayload",
    "ButtonClickPayload",
    "ButtonSpec",
    "SessionMetaPayload",
    "SlashConfirmPayload",
    "SlashPickPayload",
    "ModelPickerPayload",
    "AssistantNoticePayload",
    "AssistantSegmentPayload",
    "parse_inbound_envelope",
    "build_outbound_event",
    "normalize_mime_type",
]
